/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'audit-logs': RouteRecordInfo<'audit-logs', '/audit-logs', Record<never, never>, Record<never, never>>,
    'breakdowns': RouteRecordInfo<'breakdowns', '/breakdowns', Record<never, never>, Record<never, never>>,
    'breakdowns-manage-id': RouteRecordInfo<'breakdowns-manage-id', '/breakdowns/manage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'check-sheet-document-templates': RouteRecordInfo<'check-sheet-document-templates', '/check-sheet-document-templates', Record<never, never>, Record<never, never>>,
    'database-connections': RouteRecordInfo<'database-connections', '/database-connections', Record<never, never>, Record<never, never>>,
    'database-schema-id': RouteRecordInfo<'database-schema-id', '/database-schema/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'drawings': RouteRecordInfo<'drawings', '/drawings', Record<never, never>, Record<never, never>>,
    'dynamic-dashboard': RouteRecordInfo<'dynamic-dashboard', '/dynamic-dashboard', Record<never, never>, Record<never, never>>,
    'facilities': RouteRecordInfo<'facilities', '/facilities', Record<never, never>, Record<never, never>>,
    'facilities-manage-id': RouteRecordInfo<'facilities-manage-id', '/facilities/manage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'faq': RouteRecordInfo<'faq', '/faq', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'machines': RouteRecordInfo<'machines', '/machines', Record<never, never>, Record<never, never>>,
    'machines-manage-id': RouteRecordInfo<'machines-manage-id', '/machines/manage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'modbus-server': RouteRecordInfo<'modbus-server', '/modbus-server', Record<never, never>, Record<never, never>>,
    'mqtt-broker': RouteRecordInfo<'mqtt-broker', '/mqtt-broker', Record<never, never>, Record<never, never>>,
    'mqtt-topic': RouteRecordInfo<'mqtt-topic', '/mqtt-topic', Record<never, never>, Record<never, never>>,
    'operation': RouteRecordInfo<'operation', '/operation', Record<never, never>, Record<never, never>>,
    'parameters': RouteRecordInfo<'parameters', '/parameters', Record<never, never>, Record<never, never>>,
    'parameters-manage-id': RouteRecordInfo<'parameters-manage-id', '/parameters/manage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'permissions': RouteRecordInfo<'permissions', '/permissions', Record<never, never>, Record<never, never>>,
    'protocol-configurations': RouteRecordInfo<'protocol-configurations', '/protocol-configurations', Record<never, never>, Record<never, never>>,
    'report-document-templates': RouteRecordInfo<'report-document-templates', '/report-document-templates', Record<never, never>, Record<never, never>>,
    'smtp-server': RouteRecordInfo<'smtp-server', '/smtp-server', Record<never, never>, Record<never, never>>,
    'system-settings': RouteRecordInfo<'system-settings', '/system-settings', Record<never, never>, Record<never, never>>,
    'system-settings-dashboard-settings': RouteRecordInfo<'system-settings-dashboard-settings', '/system-settings/dashboard-settings', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'users-profile': RouteRecordInfo<'users-profile', '/users/profile', Record<never, never>, Record<never, never>>,
  }
}
