/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'alarm-logs': RouteRecordInfo<'alarm-logs', '/alarm-logs', Record<never, never>, Record<never, never>>,
    'audit-logs': RouteRecordInfo<'audit-logs', '/audit-logs', Record<never, never>, Record<never, never>>,
    'check-sheet-document-templates': RouteRecordInfo<'check-sheet-document-templates', '/check-sheet-document-templates', Record<never, never>, Record<never, never>>,
    'check-sheets': RouteRecordInfo<'check-sheets', '/check-sheets', Record<never, never>, Record<never, never>>,
    'check-sheets-approval-id': RouteRecordInfo<'check-sheets-approval-id', '/check-sheets/approval/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'check-sheets-manage-id': RouteRecordInfo<'check-sheets-manage-id', '/check-sheets/manage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'database-schema-id': RouteRecordInfo<'database-schema-id', '/database-schema/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'executive': RouteRecordInfo<'executive', '/executive', Record<never, never>, Record<never, never>>,
    'facilities': RouteRecordInfo<'facilities', '/facilities', Record<never, never>, Record<never, never>>,
    'facilities-manage-id': RouteRecordInfo<'facilities-manage-id', '/facilities/manage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'facilities-show-id': RouteRecordInfo<'facilities-show-id', '/facilities/show/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'faqs': RouteRecordInfo<'faqs', '/faqs', Record<never, never>, Record<never, never>>,
    'generate-reports': RouteRecordInfo<'generate-reports', '/generate-reports', Record<never, never>, Record<never, never>>,
    'log-alarms': RouteRecordInfo<'log-alarms', '/log-alarms', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'machines': RouteRecordInfo<'machines', '/machines', Record<never, never>, Record<never, never>>,
    'machines-dashboard-id': RouteRecordInfo<'machines-dashboard-id', '/machines/dashboard/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'machines-manage-id': RouteRecordInfo<'machines-manage-id', '/machines/manage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'machines-show-id': RouteRecordInfo<'machines-show-id', '/machines/show/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'modbus-servers': RouteRecordInfo<'modbus-servers', '/modbus-servers', Record<never, never>, Record<never, never>>,
    'mqtt-brokers': RouteRecordInfo<'mqtt-brokers', '/mqtt-brokers', Record<never, never>, Record<never, never>>,
    'mqtt-topics': RouteRecordInfo<'mqtt-topics', '/mqtt-topics', Record<never, never>, Record<never, never>>,
    'parameters': RouteRecordInfo<'parameters', '/parameters', Record<never, never>, Record<never, never>>,
    'parameters-manage-id': RouteRecordInfo<'parameters-manage-id', '/parameters/manage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'permissions': RouteRecordInfo<'permissions', '/permissions', Record<never, never>, Record<never, never>>,
    'registers': RouteRecordInfo<'registers', '/registers', Record<never, never>, Record<never, never>>,
    'registers-manage-id': RouteRecordInfo<'registers-manage-id', '/registers/manage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'report-document-templates': RouteRecordInfo<'report-document-templates', '/report-document-templates', Record<never, never>, Record<never, never>>,
    'system-settings': RouteRecordInfo<'system-settings', '/system-settings', Record<never, never>, Record<never, never>>,
    'system-settings-dashboard-settings': RouteRecordInfo<'system-settings-dashboard-settings', '/system-settings/dashboard-settings', Record<never, never>, Record<never, never>>,
    'system-settings-listener-settings': RouteRecordInfo<'system-settings-listener-settings', '/system-settings/listener-settings', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'users-profile': RouteRecordInfo<'users-profile', '/users/profile', Record<never, never>, Record<never, never>>,
  }
}
