/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'database-connections': RouteRecordInfo<'database-connections', '/database-connections', Record<never, never>, Record<never, never>>,
    'database-schema-id': RouteRecordInfo<'database-schema-id', '/database-schema/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'drawings': RouteRecordInfo<'drawings', '/drawings', Record<never, never>, Record<never, never>>,
    'dynamic-dashboard': RouteRecordInfo<'dynamic-dashboard', '/dynamic-dashboard', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'machines': RouteRecordInfo<'machines', '/machines', Record<never, never>, Record<never, never>>,
    'machines-create': RouteRecordInfo<'machines-create', '/machines/create', Record<never, never>, Record<never, never>>,
    'machines-mapping-id': RouteRecordInfo<'machines-mapping-id', '/machines/mapping/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'mqtt-topic': RouteRecordInfo<'mqtt-topic', '/mqtt-topic', Record<never, never>, Record<never, never>>,
    'operation': RouteRecordInfo<'operation', '/operation', Record<never, never>, Record<never, never>>,
    'parameters': RouteRecordInfo<'parameters', '/parameters', Record<never, never>, Record<never, never>>,
    'parameters-manage-id': RouteRecordInfo<'parameters-manage-id', '/parameters/manage/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'permissions': RouteRecordInfo<'permissions', '/permissions', Record<never, never>, Record<never, never>>,
    'protocol-configurations': RouteRecordInfo<'protocol-configurations', '/protocol-configurations', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
  }
}
